deployment:
  container:
    image:
      repository: 704855531002.dkr.ecr.us-west-2.amazonaws.com/eks-fluxcd-lab-sqs-producer
      tag: latest
    sqsQueueName: eks-fluxcd-lab-sqs-queue
  serviceAccountName: sa-aws-sqs

ingress:
  enabled: false
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-west-2:704855531002:certificate/7e180ee7-731e-41a6-905e-71a747edd5cf"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: sqs-app.dallin.brewsentry.com
  dnsHostname: sqs-app.dallin.brewsentry.com
