---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
 name: aws-sqs-queue-scaledobject
 namespace: sqs-app
spec:
  minReplicaCount: 0
  maxReplicaCount: 20
  pollingInterval: 15
  cooldownPeriod:  30
  # fallback:
  #   failureThreshold: 3
  #   replicas: 2
  scaleTargetRef:
    name: sqs-consumer
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-trigger-auth-aws-credentials
    metadata:
      queueURL: SQS_QUEUE_URL
      queueLength: "5"
      awsRegion: "AWS_REGION"
      identityOwner: operator
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  namespace: sqs-app
spec:
  podIdentity:
    provider: aws-eks
