---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sqs-consumer
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/sqs-app/sqs-consumer
      version: ">=1.0.0"
      sourceRef:
        kind: GitRepository
        name: sqs-app
        namespace: flux-system
  install:
    remediation:
      retries: 5
  values:
    deployment:
      container:
        image:
          repository: ECR_SQS_CONSUMER_REPO
          tag: latest
        sqsQueueName: SQS_QUEUE_NAME
      serviceAccountName: SA_SQS_APP_NAME
  interval: 2m0s
  releaseName: sqs-consumer
  targetNamespace: sqs-app
