deployment:
  name: sqs-consumer
  container:
    image:
      repository:
      tag: latest
    imagePullPolicy: Always
    containerPort: 8080
    sqsQueueName:
    sleepWait: 10
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 256Mi
  replicas: 1
  serviceAccountName:
