---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sqs-producer
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/sqs-app/sqs-producer
      version: ">=1.0.0"
      sourceRef:
        kind: GitRepository
        name: sqs-app
        namespace: flux-system
  values:
    deployment:
      container:
        image:
          repository: 704855531002.dkr.ecr.us-west-2.amazonaws.com/eks-keda-sqs-lab-producer
          tag: latest
        sqsQueueName: eks-keda-sqs-lab-queue
      serviceAccountName: sa-aws-sqs
    ingress:
      enabled: enabled
      annotations:
        alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
          { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
        alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-west-2:704855531002:certificate/634b8ed7-c2c0-4896-b7dd-9330daa78a1e"
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/ssl-redirect: "443"
        alb.ingress.kubernetes.io/target-type: ip
        external-dns.alpha.kubernetes.io/hostname: sqs-app.dallin.brewsentry.com
      dnsHostname: sqs-app.dallin.brewsentry.com
  interval: 2m0s
  releaseName: sqs-producer
  targetNamespace: sqs-app
